apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test-flask
  labels:
    app: backend-flask
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-flask
  template:
    metadata:
      labels:
        app: backend-flask
    spec:
      containers:
      - name: flask-app
        image: redis:alpine700
