apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: redis
        image: redis:alpine
#        envFrom: 
#        - configMapRef:
#            name: envfrom-test
#          prefix: MY_PREFIX_    
        volumeMounts:
          - name: test-conf
            mountPath: /test/config
      volumes:
        - name: test-conf
          configMap:
            name: config-file
