apiVersion: v1
kind: Pod
Mmetadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: pod-test
  labels:
    app: pod-test
spec:
  containers:
  - name: myapp
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
