apiVersion: v1
kind: Pod
metadata:
  annotations:
    argocd.argoproj.io/hook: SyncFail
    argocd.argoproj.io/hook-delete-policy: HookFailed
  name: pod-test
  labels:
    app: pod-test
spec:
  containers:
  - name: myapp
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
